"""index documents created_at

Revision ID: 54e7e318634b
Revises: c2d6d056882b
Create Date: 2026-09-14 11:41:33.145197

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "54e7e318634b"
down_revision: str | Sequence[str] | None = "c2d6d056882b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_documents_created_at"), "documents", ["created_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_documents_created_at"), table_name="documents")
    # ### end Alembic commands ###
